# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: '#about'
    weight: 10
  - name: Experience
    url: '#exp'
    weight: 20
  - name: Education
    url: '#edu'
    weight: 30
  - name: Skills
    url: '#skills'
    weight: 31
  - name: Publications
    url: '#pub'
    weight: 32
  - name: Certificates
    url: '#cert'
    weight: 33
  - name: Awards
    url: '#awd'
    weight: 40
  - name: Projects
    url: '#projects'
    weight: 50
  - name: CV
    url: uploads/resume.pdf
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
